server {
    listen 80;
    server_name ТВО_ДОМЕН;  # <- заменить на свой домен

    # certbot сам заменит этот блок на HTTPS после получения сертификата
    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
